# Generated by Django 5.2.16 on 2026-07-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron_ai_admin', '0007_ui_style_applying_lease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uistylechangerequest',
            name='status',
            field=models.CharField(choices=[('proposed', 'proposed'), ('approved', 'approved'), ('applying', 'applying'), ('applied', 'applied'), ('rejected', 'rejected'), ('conflicted', 'conflicted')], db_index=True, default='proposed', max_length=32),
        ),
    ]
