# Generated by Django 5.2.16 on 2026-07-22 13:43

import cauldron_content_operations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cauldron_content_operations', '0002_view_change_requests_and_idempotency_scoping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpermissionproxy',
            options={'default_permissions': (), 'managed': False, 'permissions': (('view_published_content', 'Can view published content'), ('view_draft_content', 'Can view draft content'), ('view_content_change_requests', 'Can view content change requests'), ('propose_content_changes', 'Can propose content changes'), ('validate_content_changes', 'Can validate content changes'), ('approve_content_changes', 'Can approve content changes'), ('reject_content_changes', 'Can reject content changes'), ('apply_content_changes', 'Can apply content changes'), ('rollback_content_changes', 'Can roll back content changes'), ('view_content_audit', 'Can view content audit history'))},
        ),
        migrations.AlterField(
            model_name='contentauditevent',
            name='event_id',
            field=models.CharField(db_index=True, default=cauldron_content_operations.models._uuid_str, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='contentchangerequest',
            name='request_id',
            field=models.CharField(db_index=True, default=cauldron_content_operations.models._uuid_str, max_length=64, unique=True),
        ),
    ]
